### ISSUE TITLE
crash enter abandoned mines

### ISSUE THREAD

**Issue by triade32** [CEObrainz/Second-Wind#34] opened 2022-06-18 17:00 UTC
Hi . I am with the secondwind mod on wiiu. the mod works very well. the only concern is when I enter the mine abandon the game crash .... the image remains fixed and the loading logo hangs.the only other mod that I have to install is infinit stamina and fast fly ... even without these mods always the same result

**Comment by CEObrainz** [comment] 2022-08-03 12:07
Duplicate of #24

**Closed by CEObrainz** 2022-08-03 12:07 UTC
Labels: duplicate
