### ISSUE TITLE
Some clothing doesn't work

### ISSUE THREAD

**Issue by Cheese2202** [CEObrainz/Second-Wind#20] opened 2022-03-18 16:42 UTC
Cheese#5865

Wii U

Nightly 2022-3-18
ver. 1.5.0
DLC ver. 3.0

When trying to equip certain types of clothing (royal guard set, phantom set, champion's tunic, and some others) they will not equip. In the menu they will be highlighted, but link will not wear them. When unequipped, they will remove whatever piece of clothing is on link. One of the amiibo items crashed the game.

Open menu, try to equip one of sets listed.

**Comment by CEObrainz** [comment] 2022-08-03 12:15
Duplicate of #24

**Closed by CEObrainz** 2022-08-03 12:15 UTC
