### ISSUE TITLE
Graphic glitches in Ordon

### ISSUE THREAD

**Issue by lntrc** [CEObrainz/Second-Wind#25] opened 2022-04-04 18:34 UTC
On the Wii U console, with v1.9.12, I get serious graphic gllitches in Ordon, specifically the east area with the store, Tara's pumpkins, mask salesman &c. Basically looks like a cracked screen with large one-color geometric shapes (triangles, rectangles) covering most of the screen, flashing on and off. More often than not the game freezes shortly afterwards. (Does SW fully support the Wii U console?)

**Comment by CEObrainz** [comment] 2022-04-04 21:59
Duplicate of #24

**Closed by CEObrainz** 2022-04-04 21:59 UTC
Labels: duplicate

**Comment by lntrc** [comment] 2022-08-03 12:58
This issue (making Ordon unplayable due to not being able to see what's happening on screen) was bundled with '#24 Lack of Navmesh and Collision Generation causing Blood Moons and Crashes' for Reasons. While blood moons and other issues mentioned in #24 happen in numerous places using the mod, the 'visual artefacts' (understatement of the year) seem to happen in Ordon only, and in a specific part of Ordon to boot. If this area is particulary sensitive to lack of navmesh &c, could the area be tweaked?
If the Wii U is not fully supported by SW, please consider informing users of this fact up front.

**Comment by CEObrainz** [comment] 2022-08-03 14:35
> 

See the Troubleshooting section in the Discord.

**Comment by lntrc** [comment] 2022-08-03 16:39
Since SW does not fully support the Wii U, please consider informing users of this fact up front (download page).
