### ISSUE TITLE
Game crashing in specific areas

### ISSUE THREAD

**Issue by SuperKoopa64** [CEObrainz/Second-Wind#36] opened 2022-07-12 14:29 UTC
After opening the EX chest by the Kolomo Garrison ruins and heading to the spring of courage where Majora's Mask is located, the game automatically crashes when I go to that area whether I'm on the ground or in the air with my paraglider, no panic blood moons occur when I'm there. 

The second area where the game crashes is in the loading zone after talking to the statue by the lake when trying to go to fight the Hinox King. This is near the Hateno Tower. 

Very occasionally in Ordon Village, the game crashes while I am walking in the village, but comes with lots of panic blood moons though. 

I hope there will be some sort of fix to these bugs in future updates.
This is in the Nightly Build and I am playing on Wii U

**Comment by CEObrainz** [comment] 2022-08-03 12:09
Duplicate of #24

**Closed by CEObrainz** 2022-08-03 12:09 UTC
